packages:
  - packages/webster-babel
  - packages/webster-eslint
  - packages/webster-postcss
  - packages/webster-prettier
  - packages/webster-stylelint
  - packages/webster-typescript

onlyBuiltDependencies:
  - core-js-pure
  - postinstall-postinstall
